version: "3.8"

services:
  # resiliantdb:
  #   image: docker.io/expolab/resdb:amd64
  #   ports:
  #     - 18000:18000
  #     - 10005:10005

  crow_server:
    build: .
    ports:
      - 18000:18000
    command: /bin/bash -c "cd /ResilientDB-GraphQL && bazel-bin/service/http_server/crow_service_main service/tools/config/interface/service.config service/http_server/server_config.config"

  # graphql_server:
  #   build: .
  #   command: /bin/bash -c "cd /ResilientDB-GraphQL && source venv/bin/activate && gunicorn -b 0.0.0.0:8000 app:app"

  # nginx:
  #   image: nginx:latest
  #   command: nginx -g 'daemon off;' -c /etc/nginx/nginx.conf
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - graphql_server
